version: '3.8'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: loja_virtual
      WORDPRESS_DB_PASSWORD: loja_virtual
      WORDPRESS_DB_NAME: loja_virtual
    volumes:
      - ./wordpress:/var/www/html  # Mapeamento do volume local para o diretório do WordPress

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: loja_virtual
      MYSQL_USER: loja_virtual
      MYSQL_PASSWORD: loja_virtual
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql  # Mapeamento do volume local para o diretório do MySQL

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  wordpress:  # Definição do volume para o WordPress
  mysql:      # Definição do volume para o MySQL