version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bbq_restaurant
      WORDPRESS_DB_PASSWORD: bbq_restaurant
      WORDPRESS_DB_NAME: bbq_restaurant
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 3306:3306      
    environment:
      MYSQL_DATABASE: bbq_restaurant
      MYSQL_USER: bbq_restaurant
      MYSQL_PASSWORD: bbq_restaurant
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080      

volumes:
  wordpress:
  db: