version: '3.8'

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: bbq_restaurant
      WORDPRESS_DB_PASSWORD: bbq_restaurant
      WORDPRESS_DB_NAME: bbq_restaurant
    volumes:
      - ./wordpress:/var/www/html  # Mapeamento do volume local para o diretório do WordPress
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always  
    environment:
      MYSQL_DATABASE: bbq_restaurant
      MYSQL_USER: bbq_restaurant
      MYSQL_PASSWORD: bbq_restaurant
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql  # Mapeamento do volume local para o diretório do MySQL

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080  
    depends_on:
      - mysql    

volumes:
  wordpress:  # Definição do volume para o WordPress
  mysql:      # Definição do volume para o MySQL